name: CI

on:
  push:
    branches: [develop]

permissions:
  contents: read

concurrency: ci

jobs:
  test:
    name: Validate on ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Go
        id: install_go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Check formatting
        id: check_fmt
        run: |
          test -z "$(gofmt -l .)"

      - name: Vet
        id: vet
        run: |
          go vet ./...

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: start-mongodb
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: "7.0"

      - name: Test
        id: test
        env:
          TEST_DB_URI: "mongodb://localhost:27017/unit-tests"
          TEST_COLLECTION: unit-tests
          LOG_LEVEL: DEBUG
        run: |
          go test -race -coverprofile coverage.out ./...
          go tool cover -func coverage.out
          mkdir coverage
          go tool cover -html coverage.out -o coverage/coverage.html

      - name: Publish coverage
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
