name: CI

concurrency: ci

on:
    push:
        branches: [develop]
        paths:
            - "**/*.go"
            - go.mod
            - go.sum
            - .go-version
    workflow_dispatch:
    repository_dispatch:
        types:
            - deps-updated

permissions:
    contents: write

jobs:
    tests:
        name: Build/test for ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Linux
                      os: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version-file: go.mod
            - name: Build
              run: go build -v ./...
            - name: start-mongodb
              uses: supercharge/mongodb-github-action@1.12.0
              with:
                mongodb-version: "7.0"
            - name: Test
              env:
                TEST_DB_URI: "mongodb://localhost:27017/unit-tests"
                TEST_COLLECTION: unit-tests
                LOG_LEVEL: DEBUG
              run: |
                go test -v -coverprofile coverage.out ./...
                go tool cover -func coverage.out
                mkdir coverage
                go tool cover -html coverage.out -o coverage/coverage.html
            - name: publish-docs
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./coverage

    #    docs:
    #        needs: [tests]
    #        runs-on: ubuntu-latest
    #        concurrency: docs
    #        steps:
    #            - uses: actions/checkout@v5
    #            - uses: actions/setup-python@v5
    #              with:
    #                  python-version: "3.11"
    #            - name: install-deps
    #              run: pip install -r requirements/docs.txt
    #            - name: make-docs
    #              run: cd docs && make html
    #            - name: publish-docs
    #              uses: peaceiris/actions-gh-pages@v3
    #              with:
    #                  github_token: ${{ secrets.GITHUB_TOKEN }}
    #                  publish_dir: ./docs/_build/html

    tag:
        needs: [tests]
        runs-on: ubuntu-latest
        concurrency: publish
        steps:
            - uses: actions/checkout@v5
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  DEFAULT_BUMP: patch

    publish:
        needs: [tag]
        runs-on: ubuntu-latest
        concurrency: publish
        steps:
            - uses: actions/checkout@v5
            - name: Get latest tag
              id: get_latest_tag
              uses: actions-ecosystem/action-get-latest-tag@v1
            - name: Publish
              env:
                GOPROXY: proxy.golang.org
              run: go list -m github.com/${{ github.repository }}@${{ steps.get_latest_tag.outputs.tag }}

    notify:
        needs: [tag]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - repo: api-core.go
                    - repo: catalog-api
                    - repo: catalog-data.go
                    - repo: catalog-data-processor
                    - repo: catalog-objects.go
                    - repo: catalog-web
                    - repo: client.go
                    - repo: data-api
                    - repo: data-objects.go
                    - repo: mongodb.go
                    - repo: initiative-api
                    - repo: initiative-data.go
                    - repo: initiative-objects.go
                    - repo: initiative-web
                    - repo: kv-api
                    - repo: kv-data.go
                    - repo: kv-expression-processor
                    - repo: kv-key-processor
                    - repo: kv-objects.go
                    - repo: kv-value-calculator
                    - repo: kv-web
                    - repo: library-api
                    - repo: library-data.go
                    - repo: library-objects.go
                    - repo: library-web
                    - repo: main-web
                    - repo: model-core.go
                    - repo: shared-web
                    - repo: web-core.go
        steps:
            - uses: juztcode/repo-ditpatch-action@v1
              continue-on-error: true
              with:
                event-type: db-published
                token: ${{ secrets.REPO_ACCESS_TOKEN }}
                repository: sweetrpg/${{ matrix.repo }}
